name: .NET

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      working-directory: ./Source
      run: dotnet restore
      
    - name: Build
      working-directory: ./Source
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: ./Source
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: ./build.bat
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: pub/*.*
